accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.loginview, name='login'),
    path('logout/', views.logoutview, name='logout')
]

posts/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.conf import settings 
from django.conf.urls.static import static



app_name = 'posts'

urlpatterns = [
    path('create/', views.create, name='create'),
    url(r'^(?P<pk>[0-9]+)/upvote', views.upvote, name='upvote'),
    url(r'^(?P<pk>[0-9]+)/downvote', views.downvote, name='downvote'),
    url(r'^user/(?P<fk>[0-9]+)', views.userposts, name='userposts'),
    path('comment/', views.comment, name='comment'),
] 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

redditclone/urls.py
from django.contrib import admin
from django.urls import path, include
import accounts.views
from posts import views

from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('', views.home, name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=200, default='')
    site_url = models.TextField(default='')
    content = models.TextField(default="")
    created_at = models.DateTimeField(blank=True, null=True)
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    votes_total = models.IntegerField(default=1)
    image = models.FileField(upload_to='images', blank=True)
    

    def created_at_formatted(self):
        return self.created_at.strftime('%b %e %Y')

class Comment(models.Model):
    title = models.CharField(max_length=200, default='')
    content = models.TextField(default="")
    created_at = models.DateTimeField(blank=True, null=True)
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    posts = models.ForeignKey(Post, on_delete= models.CASCADE, null=True)
    votes_total = models.IntegerField(default=1)
  


    def created_at_formatted(self):
        return self.created_at.strftime('%b %e %Y')

posts/forms.py
from django import forms
from .models import Post, Comment
from django.contrib.auth.models import User

class PostForm(forms.ModelForm):
    class Meta: 
        model = Post
        fields = ('title','content') 


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('title','content','picture','vote_total','')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

def signup(request):
    if request.method == 'POST':
        #check for password matching
        if request.POST['password1'] == request.POST['password2']:
            #try to get a user with name and check to see 
                try:
                    user = User.objects.get(username=request.POST['username'])
                    return render(request,'accounts/signup.html',{'Error': 'Username has already been taken. Please select a different username'})
                    #create user sending data given in request
                except User.DoesNotExist:
                    user = User.objects.create_user(request.POST['username'], email=request.POST['email'], password=request.POST['password1'])
                    #upon account creation, login user and prevent user from viewing admin page
                    login(request,user)
                    return render(request,'accounts/signup.html', {'Success':'Account successfully created'})
        else:
            return render(request,'accounts/signup.html', {'Error':'Passwords didn\'t match'})
    else:
        return render(request,'accounts/signup.html')


def loginview(request):
    if request.method == 'POST':
        #check for password matching
        user = authenticate(username=request.POST['username'], password=request.POST['password1'])
        if user is not None:
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST['next'])
            return redirect('home')
        else:
            return render(request,'accounts/login.html', {'Error':'Username/Passwords didn\'t match. Please try again.'})
    else:
        return render(request,'accounts/login.html')

def logoutview(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')

posts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from .models import Post, Comment
from django.contrib.auth.models import User


@login_required
def create(request):
    if request.method == 'POST':
        if request.POST['title'] and request.POST['url'] and request.POST['content']:
            post = Post()
            post.title = request.POST['title']
            if request.POST['url'].startswith('http://') or request.POST['url'].startswith('https://'):
                post.url = request.POST['url']
            else:
                post.url = 'http://' + request.POST['url']
            post.created_at = timezone.datetime.now()
            post.user = request.user
            post.save()
            return redirect('home')
        else:
            return render(request,'posts/create.html',{'error':'Please fill out required fields marked with * to create a post.'})
    else:
        return render(request, 'posts/create.html')

def home(request):
    post = Post.objects.order_by('-votes_total')
    return render(request, 'posts/home.html', {'posts':post})

def upvote(request, pk):
    #only for get requests
    if request.method == 'POST':
        post = Post.objects.get(pk=pk)
        post.votes_total += 1
        post.save()
        return redirect('home')

def downvote(request, pk):
    if request.method == 'POST':
        post = Post.objects.get(pk=pk)
        post.votes_total -= 1 
        post.save()
        return redirect('home')

def userposts(request, fk):
    posts = Post.objects.filter(user__id=fk).order_by('-votes_total')
    user = User.objects.get(pk=fk)
    return render(request,'posts/userposts.html', {'posts':posts,'user':user})
  
def comment(request):
    if request.method == 'POST':
        if request.POST['title'] and request.POST['content']: 
            comment = Comment()
            comment.title = request.POST['title']
            comment.content = request.POST['content']
            comment.created_at = timezone.datetime.now()
            comment.user = request.user
            comment.save()
            return redirect('home')
        else: 
            # return render(request,'posts/comment.html',{'error':'Please fill out required fields.'})
            return redirect('home')
    else:
        return render(request, 'posts/comment.html')

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<h1>Login</h1>
<!-- Message for problems with account creation -->
{% if Error %}
{{ Error }}
{% endif %}


<form method ="POST" action="{% url 'accounts:login' %}">
    {% csrf_token %}
    
    <!-- if there's a next on login page, send hidden form -->
    {% if request.GET.next %}
    <input type="hidden" name="next" value={{ request.GET.next }} />
    {% endif %}

    <label for "username">Username</label>
        <input type="text" name="username" />
    <br />
    <label for "password1">Password</label>
        <input type="password" name="password1" />
    <br />
    <input class="btn btn-primary" type="submit" value="Log In" />
</form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}

<h1>Sign Up</h1>
<!-- Message for problems with account creation -->
{% if Error %}
{{ Error }}
{% endif %}
<!-- Message for successful account creation -->
{% if Success %}
{{ Success }}
{% endif %}

<form method ="POST" action="{% url 'accounts:signup' %}">
    {% csrf_token %}
    <label for "username">Username</label>
        <input type="text" name="username" />
    <br />
    <label for "email">Email</label>
        <input type="text" name="email" />
    <br />
    <label for "password1">Password</label>
        <input type="password" name="password1" />
    <br />
    <label for "password2">Confirm Password</label>
        <input type="password" name="password2" /> 
    <br />
    <input class="btn btn-primary" type="submit" value="Submit" />
</form>
{% endblock %}

posts/templates/posts/comment.html
{% extends 'base.html' %}

{% block content %}
<h1>New Comment</h1>

{% if error %}
{{ error }}
<br />
<br />
{% endif %}

<form method="POST" action="{% url 'posts:comment' %}">
  {% csrf_token %}

  Title*:
  <br />
  <input type="text" name="title" />
  <br />
  Content*:
  <br />
  <input type="text" name="content" />
  <br />
  <br />
  <input class="btn btn-primary" type="submit" value="Post">
</form>

{% endblock %}

posts/templates/posts/create.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<h1>New Post</h1>

{% if error %}
{{ error }}
<br />
<br />
{% endif %}

<form enctype="multipart/form-data" method="POST" action="{% url 'posts:create' %}">
  {% csrf_token %}

  Title*:
  <br />
  <input type="text" name="title" />
  <br />
  URL*:
  <br />
  <input type="text" name="url" />
  <br />
  Image:
  <br />
  <input type="text" name="image" />
  <br />
  Content*:
  <br />
  <input type="text" name="content" />
  <br />
  <br />
  <input class="btn btn-primary" type="submit" value="Post">
</form>

{% endblock %}

posts/templates/posts/home.html
{% extends 'base.html' %}

{% block content %}

<h1>r/aww</h1>
<a class = "btn btn-primary" href="{% url 'posts:create' %}">New Post</a>
<br />
<br />
<!-- Posts -->
{% for post in posts.all %}

    <a href="#" onClick="document.getElementById('upvote{{ post.id }}').submit()"><span class="glyphicon glyphicon-triangle-top" aria-hidden="true"></span></a>
    {{ post.votes_total }} 
    <a href="#" onClick="document.getElementById('downvote{{ post.id }}').submit()"><span class="glyphicon glyphicon-triangle-bottom" aria-hidden="true"></span></a>

    <form id="upvote{{ post.id }}" method="POST" action="{% url 'posts:upvote' post.id %}">
        {% csrf_token %}
        <input type="hidden">
    </form> 
    <form id="downvote{{ post.id }}" method="POST" action="{% url 'posts:downvote' post.id %}">
        {% csrf_token %}
        <input type="hidden">
    </form>  - <a href="{{ post.site_url }}"> {{ post.title }} </a>

    <br />
    {{ post.created_at_formatted }} by <a href="{% url 'posts:userposts' post.user.id %}">{{ post.user.username }}</a>
    <br />
    <img src="{{ post.image.url }}" width="250">
    <br />
    {{ post.content }}
    <br />

    <br />
    <a class = "btn btn-primary" href="{% url 'posts:comment'  %}">Comment</a>

    <br />


    <!-- not working - revisit -->
    <h5>Comments</h5>
    {% for comment in posts.all %}

        <p>{{ comment.title }} by {{ comment.user }}</p>
        <p>{{ comment.content }}</p>
        <p>{{ comment.created_at }}</p>
     
        <hr>
        {% empty %}
            <p>FIRST COMMENT</p>
    
    {% endfor %}
<hr>

{% endfor %}

<!-- Comments -->


{% endblock %}

posts/templates/posts/userposts.html
{% extends 'base.html' %}

{% block content %}

<h1>All Posts By {{ user.username }} </h1>

<br />


{% for post in posts.all %}
<a href="#" onClick="document.getElementById('upvote{{ post.id }}').submit()"><span class="glyphicon glyphicon-triangle-top" aria-hidden="true"></span></a>
{{ post.votes_total }} 
<a href="#" onClick="document.getElementById('downvote{{ post.id }}').submit()"><span class="glyphicon glyphicon-triangle-bottom" aria-hidden="true"></span></a>

<form id="upvote{{ post.id }}" method="POST" action="{% url 'posts:upvote' post.id %}">
    {% csrf_token %}
    <input type="hidden">
 </form> 
 <form id="downvote{{ post.id }}" method="POST" action="{% url 'posts:downvote' post.id %}">
    {% csrf_token %}
    <input type="hidden">
</form>  - <a href="{{ post.site_url }}"> {{ post.title }} </a>

<br />
{{ post.created_at_formatted }} by <a href="{% url 'posts:userposts' post.user.id %}">{{ post.user.username }}</a>
<br />
{{ post.content }}
<br />
<img src="{{ post.image.url }}" /> 

<br />
<hr>


{% endfor %}

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Reddit</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>

    <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mynav">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">reddit</a>
        </div>
        <div class="collapse navbar-collapse" id="mynav">
          <ul class="nav navbar-nav navbar-right">
              {% if user.is_authenticated %}
              <li><a href= "#" onClick="document.getElementById('logout').submit()">Log Out</a></li>
              <form id="logout" method="POST" action="{% url 'accounts:logout' %}">
                  {% csrf_token %}
                  <input type="hidden">
              </form>
              {% else %}
              <li><a href="{% url 'accounts:signup' %}">Sign Up</a> </li>
              <li><a href="{% url 'accounts:login' %}">Log In</a> </li>
              {% endif %}
               
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      {% block content %}
      {% endblock %}
    </div>

   
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>